# Site settings
title: stjerneman.com
url: https://stjerneman.com
version: 1.0.2
author:
  name: Emil Stjerneman

# Handling Reading
exclude: [
  "node_modules",
  "gulpfile.js",
  "bower.json",
  "package.json",
  "package-lock.json",
  "Gemfile",
  "Gemfile.lock"
]

excerpt_separator: <!--more-->

# Serving
baseurl: "" # the subpath of your site, e.g. /blog

# Outputting
permalink: /posts/:year/:month/:day/:title/
timezone: Europe/Stockholm

collections:
  portfolio:
    output: true
    permalink: /portfolio/:title/
    sort_by: date

